name: flutter_web_demo
description: App built using Flutter

environment:
  sdk: ">=2.9.0-8.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.1.0
  http: ^0.12.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - icons/left_arrow.png
