name: flutter_web_demo
description: App built using Flutter

environment:
  sdk: ">=2.7.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.0
  built_value: ^7.0.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  built_value_generator: ^7.0.0
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
  assets:
    - icons/left_arrow.png
