name: flutter_web_demo
description: An app built using Flutter for web

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.7.1
  flutter_web_ui: any
  flutter_web: any
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.6.7
  build_web_compilers: ^2.2.3
  built_value_generator: ^6.7.1
  pedantic: ^1.8.0+1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui